services:
 - type: worker
   name: kerm-md-demo
   env: docker
   plan: free
   dockerfilePath: ./Dockerfile
   envVars:
    - key: SESSION_ID
      value: 
    - key: BOT_INFO
      value: KÉ¢á´›á´‡á´„Êœ;à¼ºğŠğ„ğ‘ğŒ-ğ‹ğˆğ“ğ„à¼»
    - key: SUDO
      value: 237656520674
    - key: ANTILINK
      value: "true"
